-- 코드를 입력하세요
SELECT A.AUTHOR_ID
, AUTHOR_NAME
, CATEGORY
, SUM(PRICE * SALES) AS TOTAL_SALES
FROM BOOK B
, AUTHOR A
, BOOK_SALES C
WHERE B.BOOK_ID = C.BOOK_ID
AND B.AUTHOR_ID = A.AUTHOR_ID
AND TO_CHAR(C.SALES_DATE, 'YYYYMM') = '202201'
GROUP BY A.AUTHOR_ID
, AUTHOR_NAME
, CATEGORY
ORDER BY A.AUTHOR_ID ASC
, CATEGORY DESC;